### PR TITLE
Asynchronous Filtering

### PR DESCRIPTION
**Pull request by brandons**
In our app we needed to be able to make a network request to get autocomplete suggestions. This adds `asyncFilterFunction` with a callback so the suggestions can be updated later. An example of it's use is below. Let me know if you're interested in merging and I'm happy to update the example project. 

Thanks!

```
<<< SuggestionAccessoryRow<Brand>("brandRow") {
  $0.placeholder = ""
  $0.asyncFilterFunction = { (string, filterCompletion) in
      APIClient.search(for: string, withCompletion: { (results, error) in
	filterCompletion(results)
 })
}}
```

### CODE REVIEW

**Comment by TheJuki** [comment]
This is great! Thank you.

**Comment by brandons** [comment]
@TheJuki Can we merge this?

**Comment by TheJuki** [comment]
@brandons I don't own this project. I used your fork in my app and the asynchronous filtering worked great.

**Comment by brandons** [comment]
@mats-claassen  Can we get this merged in?

**Comment by mats-claassen** [comment]
@brandons Sorry for the late response. Could you remove the change in the podspec as this has been updated in master?

**Comment by kamerc** [comment]
@brandons can you fix the podspec conflict and merge this in? I need to use your changes and would prefer it to be in the production build.

**Comment by brandons** [comment]
Podspec file reverted :)

**Pull request merged**
